# Generated by Django 3.0.5 on 2020-12-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('emailid', models.EmailField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=10)),
                ('age', models.PositiveSmallIntegerField(default=0, max_length=3)),
                ('gender', models.PositiveSmallIntegerField(default=0, max_length=1)),
            ],
        ),
    ]
