# Generated by Django 3.0.5 on 2020-12-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signup',
            name='gender',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
