# Generated by Django 3.0.5 on 2021-01-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20201201_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.EmailField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=30)),
                ('name', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=10)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('gender', models.PositiveSmallIntegerField(default=0)),
                ('prooffile', models.FileField(upload_to='D:Final Year Project/Manovaidya/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.EmailField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=30)),
                ('name', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=10)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('gender', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
