# Generated by Django 3.0.5 on 2021-02-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20210131_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistsignup',
            name='prooffile',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
