# Generated by Django 3.0.5 on 2021-03-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20210325_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.EmailField(default='', max_length=200)),
                ('therapistemail', models.EmailField(default='', max_length=200)),
                ('date', models.PositiveSmallIntegerField(default=0)),
                ('month', models.PositiveSmallIntegerField(default=0)),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('time', models.PositiveSmallIntegerField(default=0)),
                ('roomid', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
